#!/usr/bin/env python3
"""
High-Frequency Trading FIX Engine - Interactive Performance Plotter
Reads 'metrics_time_series.csv' generated by CsvPerformanceMonitor (Thread 4)
and plots a multi-panel interactive chart using 'pandas' and 'plotly'.
It displays exact values on hover, locks zooming across axes, and opens in the browser.
"""

import sys
import os
import argparse
import webbrowser

try:
    import pandas as pd
    import plotly.graph_objects as go
    from plotly.subplots import make_subplots
except ImportError as e:
    print(f"[Error] Required Python package missing: {e}")
    print("Please activate the virtual environment or install required libraries using:")
    print("  python3 -m venv .venv && .venv/bin/pip install -r requirements.txt")
    print("  # Or directly: pip install pandas plotly")
    sys.exit(1)


def plot_telemetry_interactive(csv_path: str, output_html: str):
    if not os.path.exists(csv_path):
        print(f"[Error] CSV file not found at: {csv_path}")
        print("Run the C++ engine first (e.g., sudo ./build/bin/hft_fix_engine lo 8888 50000) to generate telemetry data.")
        sys.exit(1)

    print(f"Loading telemetry data from: {csv_path} using Pandas...")
    df = pd.read_csv(csv_path)

    if df.empty:
        print("[Warning] CSV file is empty. Nothing to plot.")
        sys.exit(0)

    # Ensure required columns are present in dataframe
    # Ensure required columns are present in dataframe (with graceful fallbacks for older CSVs)
    if "risk_approved" not in df.columns:
        df["risk_approved"] = df["total_processed"]
    if "risk_rejected" not in df.columns:
        df["risk_rejected"] = 0
    if "approved_avg_latency_ns" not in df.columns:
        df["approved_avg_latency_ns"] = df["avg_latency_ns"]
    if "rejected_avg_latency_ns" not in df.columns:
        df["rejected_avg_latency_ns"] = 0.0

    # Create subplots with 2 rows and 2 columns, sharing X axes
    fig = make_subplots(
        rows=2, cols=2,
        shared_xaxes=True,
        vertical_spacing=0.12,
        horizontal_spacing=0.08,
        subplot_titles=(
            "Instantaneous Processing Throughput",
            "Latency Breakdown: Approved vs Rejected Risk Validation (Log Scale)",
            "Lock-Free SPSC Queue Instantaneous Depth",
            "Risk Validation & Cumulative Message Progression"
        )
    )

    # Panel 1: Throughput (Top Left)
    fig.add_trace(
        go.Scatter(
            x=df["elapsed_sec"],
            y=df["throughput_msg_sec"],
            mode="lines",
            name="Throughput",
            line=dict(color="#1f77b4", width=2.5),
            fill="tozeroy",
            fillcolor="rgba(31, 119, 180, 0.15)",
            hovertemplate="Throughput: %{y:,.0f} msgs/sec<extra></extra>"
        ),
        row=1, col=1
    )

    # Panel 2: Latencies (Top Right)
    fig.add_trace(
        go.Scatter(
            x=df["elapsed_sec"],
            y=df["avg_latency_ns"],
            mode="lines",
            name="Overall Avg Latency",
            line=dict(color="#2ca02c", width=2.5),
            hovertemplate="Overall Avg Latency: %{y:.1f} ns<extra></extra>"
        ),
        row=1, col=2
    )
    fig.add_trace(
        go.Scatter(
            x=df["elapsed_sec"],
            y=df["approved_avg_latency_ns"],
            mode="lines",
            name="Approved Avg Latency",
            line=dict(color="#17becf", width=2.0),
            hovertemplate="Approved Avg Latency: %{y:.1f} ns<extra></extra>"
        ),
        row=1, col=2
    )
    fig.add_trace(
        go.Scatter(
            x=df["elapsed_sec"],
            y=df["rejected_avg_latency_ns"],
            mode="lines",
            name="Rejected Avg Latency",
            line=dict(color="#d62728", width=2.0, dash="dash"),
            hovertemplate="Rejected Avg Latency: %{y:.1f} ns<extra></extra>"
        ),
        row=1, col=2
    )
    fig.add_trace(
        go.Scatter(
            x=df["elapsed_sec"],
            y=df["min_latency_ns"],
            mode="lines",
            name="Min Latency",
            line=dict(color="#9467bd", width=1.5, dash="dot"),
            hovertemplate="Min Latency: %{y:.1f} ns<extra></extra>"
        ),
        row=1, col=2
    )

    # Panel 3: Queue Depth (Bottom Left)
    fig.add_trace(
        go.Scatter(
            x=df["elapsed_sec"],
            y=df["spsc_queue_depth"],
            mode="lines",
            name="SPSC Queue Depth",
            line=dict(color="#9467bd", width=2.5),
            fill="tozeroy",
            fillcolor="rgba(148, 103, 189, 0.15)",
            hovertemplate="Queue Depth: %{y} items<extra></extra>"
        ),
        row=2, col=1
    )

    # Panel 4: Cumulative Captured vs. Processed & Risk Breakdown (Bottom Right)
    fig.add_trace(
        go.Scatter(
            x=df["elapsed_sec"],
            y=df["rx_frames_captured"],
            mode="lines",
            name="Captured Frames",
            line=dict(color="#ff7f0e", width=2.5),
            hovertemplate="Frames Captured: %{y:,.0f}<extra></extra>"
        ),
        row=2, col=2
    )
    fig.add_trace(
        go.Scatter(
            x=df["elapsed_sec"],
            y=df["total_processed"],
            mode="lines",
            name="Total Processed",
            line=dict(color="#8c564b", width=2.0),
            hovertemplate="Total Processed: %{y:,.0f}<extra></extra>"
        ),
        row=2, col=2
    )
    fig.add_trace(
        go.Scatter(
            x=df["elapsed_sec"],
            y=df["risk_approved"],
            mode="lines",
            name="Risk Approved",
            line=dict(color="#2ca02c", width=1.8, dash="dash"),
            hovertemplate="Risk Approved: %{y:,.0f}<extra></extra>"
        ),
        row=2, col=2
    )
    fig.add_trace(
        go.Scatter(
            x=df["elapsed_sec"],
            y=df["risk_rejected"],
            mode="lines",
            name="Risk Rejected",
            line=dict(color="#d62728", width=1.8, dash="dot"),
            hovertemplate="Risk Rejected: %{y:,.0f}<extra></extra>"
        ),
        row=2, col=2
    )

    # Label Axes
    fig.update_xaxes(title_text="Elapsed Time (seconds)", row=2, col=1)
    fig.update_xaxes(title_text="Elapsed Time (seconds)", row=2, col=2)
    fig.update_yaxes(title_text="Throughput (msgs/sec)", tickformat=",.0f", row=1, col=1)
    fig.update_yaxes(title_text="Latency (nanoseconds) - Log Scale", type="log", row=1, col=2)
    fig.update_yaxes(title_text="Queue Occupancy (Max 8,192)", row=2, col=1)
    fig.update_yaxes(title_text="Total Message Count", tickformat=",.0f", row=2, col=2)

    # Layout styling (premium dark theme)
    fig.update_layout(
        title={
            'text': "HFT FIX Engine - Real-Time Telemetry & Zero-Copy RX Ring Bypass",
            'y': 0.97, 'x': 0.5, 'xanchor': 'center', 'yanchor': 'top'
        },
        template="plotly_dark",
        height=850,
        hovermode="x unified",
        showlegend=True,
        legend=dict(
            orientation="h",
            yanchor="bottom",
            y=1.02,
            xanchor="center",
            x=0.5
        ),
        margin=dict(t=120, b=50, l=70, r=40)
    )

    # Save output to HTML file
    out_abspath = os.path.abspath(output_html)
    fig.write_html(out_abspath, auto_open=False)
    print(f"\n[Success] Interactive telemetry dashboard saved to: {out_abspath}")

    # Print summary metrics to terminal
    valid_mins = df[df["min_latency_ns"] > 0]["min_latency_ns"]
    min_lat_observed = valid_mins.min() if not valid_mins.empty else 0.0

    print("\n====================================================")
    print("        PANDAS TELEMETRY STATISTICAL SUMMARY        ")
    print("====================================================")
    print(f"Total Samples Recorded     : {len(df)}")
    print(f"Total Duration Monitored   : {df['elapsed_sec'].max():.4f} seconds")
    print(f"Peak Throughput Recorded   : {df['throughput_msg_sec'].max():,.0f} msgs/sec")
    print(f"Average Throughput         : {df['throughput_msg_sec'].mean():,.0f} msgs/sec")
    print(f"Overall Mean Latency       : {df['avg_latency_ns'].mean():.2f} ns")
    print(f"Minimum Observed Latency   : {min_lat_observed:.0f} ns")
    print(f"Maximum Observed Latency   : {df['max_latency_ns'].max():.0f} ns")
    print(f"Max SPSC Queue Backpressure: {df['spsc_queue_depth'].max()} items")
    print("====================================================\n")

    # Launch browser window to show the plot
    print("Opening interactive Plotly dashboard in your default browser...")
    webbrowser.open(f"file://{out_abspath}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Plot HFT FIX Engine telemetry interactively using Plotly.")
    parser.add_argument("--csv", default="fix_metrics_time_series.csv", help="Path to input telemetry CSV file.")
    parser.add_argument("--out", default="hft_performance_interactive.html", help="Path for output interactive HTML file.")
    args = parser.parse_args()

    plot_telemetry_interactive(args.csv, args.out)
