#!/usr/bin/env python3
"""
High-Frequency Trading FIX Engine - Performance Visualization Script
Reads 'metrics_time_series.csv' generated by CsvPerformanceMonitor (Thread 4)
and plots a publication-quality multi-panel telemetry chart using 'pandas' and 'matplotlib'.
"""

import sys
import os
import argparse

try:
    import pandas as pd
    import matplotlib.pyplot as plt
    import matplotlib.ticker as ticker
except ImportError as e:
    print(f"[Error] Required Python package missing: {e}")
    print("Please activate the virtual environment or install required libraries using:")
    print("  python3 -m venv .venv && .venv/bin/pip install -r requirements.txt")
    print("  # Or directly: pip install pandas matplotlib")
    sys.exit(1)


def plot_telemetry(csv_path: str, output_image: str, show_plot: bool = False):
    if not os.path.exists(csv_path):
        print(f"[Error] CSV file not found at: {csv_path}")
        print("Run the C++ engine first (e.g., sudo ./build/bin/hft_fix_engine lo 8888 50000) to generate telemetry data.")
        sys.exit(1)

    print(f"Loading telemetry data from: {csv_path} using Pandas ...")
    df = pd.read_csv(csv_path)

    if df.empty:
        print("[Warning] CSV file is empty. Nothing to plot.")
        sys.exit(0)

    # Ensure required columns are present in dataframe (with graceful fallbacks for older CSVs)
    if "risk_approved" not in df.columns:
        df["risk_approved"] = df["total_processed"]
    if "risk_rejected" not in df.columns:
        df["risk_rejected"] = 0
    if "approved_avg_latency_ns" not in df.columns:
        df["approved_avg_latency_ns"] = df["avg_latency_ns"]
    if "rejected_avg_latency_ns" not in df.columns:
        df["rejected_avg_latency_ns"] = 0.0

    # Vectorized conversion of throughput to thousands (k msgs/sec)
    df["throughput_k"] = df["throughput_msg_sec"] / 1000.0

    # Setup publication-quality dark/light styled plot
    plt.style.use('seaborn-v0_8-darkgrid' if 'seaborn-v0_8-darkgrid' in plt.style.available else 'default')
    fig, axs = plt.subplots(2, 2, figsize=(16, 10), dpi=150)
    fig.suptitle("High-Frequency Trading Engine - Risk Validation & Order Telemetry", fontsize=16, fontweight='bold', y=0.96)

    # Panel 1: Throughput over time (Top Left)
    ax1 = axs[0, 0]
    ax1.plot(df["elapsed_sec"], df["throughput_k"], color='#1f77b4', linewidth=2.0, label="Throughput")
    ax1.fill_between(df["elapsed_sec"], df["throughput_k"], color='#1f77b4', alpha=0.15)
    ax1.set_title("Instantaneous Processing Throughput", fontsize=13, fontweight='bold')
    ax1.set_xlabel("Elapsed Time (seconds)")
    ax1.set_ylabel("Speed (Thousands of Msgs/sec)")
    ax1.yaxis.set_major_formatter(ticker.StrMethodFormatter('{x:,.0f}k'))
    ax1.legend(loc="upper right")
    ax1.grid(True, linestyle='--', alpha=0.6)

    # Panel 2: Latency breakdown by Risk Status (Top Right)
    ax2 = axs[0, 1]
    ax2.plot(df["elapsed_sec"], df["avg_latency_ns"], color='#2ca02c', linewidth=2.0, label="Overall Avg Latency")
    ax2.plot(df["elapsed_sec"], df["approved_avg_latency_ns"], color='#17becf', linewidth=1.8, linestyle='-', label="Approved Latency")
    ax2.plot(df["elapsed_sec"], df["rejected_avg_latency_ns"], color='#d62728', linewidth=1.8, linestyle='--', label="Rejected Latency")
    ax2.plot(df["elapsed_sec"], df["min_latency_ns"], color='#9467bd', linestyle=':', label="Min Latency")
    ax2.set_title("Latency Breakdown: Approved vs Rejected Risk Validation", fontsize=13, fontweight='bold')
    ax2.set_xlabel("Elapsed Time (seconds)")
    ax2.set_ylabel("Latency (nanoseconds)")
    ax2.set_yscale('log')
    ax2.legend(loc="upper right")
    ax2.grid(True, linestyle='--', alpha=0.6)

    # Panel 3: Lock-Free SPSC Queue Fill Depth (Bottom Left)
    ax3 = axs[1, 0]
    ax3.plot(df["elapsed_sec"], df["spsc_queue_depth"], color='#9467bd', linewidth=2.0)
    ax3.fill_between(df["elapsed_sec"], df["spsc_queue_depth"], color='#9467bd', alpha=0.2)
    ax3.set_title("Lock-Free SPSC Queue Instantaneous Depth", fontsize=13, fontweight='bold')
    ax3.set_xlabel("Elapsed Time (seconds)")
    ax3.set_ylabel("Pending Items in Queue (Max Capacity 8,192)")
    ax3.set_ylim(bottom=0)
    ax3.grid(True, linestyle='--', alpha=0.6)

    # Panel 4: Risk Validation Decisions & Cumulative Progression (Bottom Right)
    ax4 = axs[1, 1]
    ax4.plot(df["elapsed_sec"], df["rx_frames_captured"], color='#ff7f0e', linewidth=2.0, label="RX Frames Captured")
    ax4.plot(df["elapsed_sec"], df["total_processed"], color='#8c564b', linestyle='-', linewidth=2.0, label="Total Processed")
    ax4.plot(df["elapsed_sec"], df["risk_approved"], color='#2ca02c', linestyle='--', linewidth=1.8, label="Risk Approved")
    ax4.plot(df["elapsed_sec"], df["risk_rejected"], color='#d62728', linestyle=':', linewidth=1.8, label="Risk Rejected")
    ax4.set_title("Risk Validation & Cumulative Message Progression", fontsize=13, fontweight='bold')
    ax4.set_xlabel("Elapsed Time (seconds)")
    ax4.set_ylabel("Total Message Count")
    ax4.yaxis.set_major_formatter(ticker.StrMethodFormatter('{x:,.0f}'))
    ax4.legend(loc="upper left")
    ax4.grid(True, linestyle='--', alpha=0.6)

    plt.tight_layout(rect=[0, 0.03, 1, 0.94])
    plt.savefig(output_image, format='png', bbox_inches='tight')
    print(f"\n[Success] High-resolution telemetry chart saved to: {os.path.abspath(output_image)}")

    if show_plot:
        print("Displaying interactive plot on screen. Close the window to finish...")
        plt.show()

    # Print Pandas-powered statistical summary to console
    valid_mins = df[df["min_latency_ns"] > 0]["min_latency_ns"]
    min_lat_observed = valid_mins.min() if not valid_mins.empty else 0.0

    final_row = df.iloc[-1]
    print("\n====================================================")
    print("        PANDAS TELEMETRY STATISTICAL SUMMARY        ")
    print("====================================================")
    print(f"Total Samples Recorded     : {len(df)}")
    print(f"Total Duration Monitored   : {df['elapsed_sec'].max():.4f} seconds")
    print(f"Peak Throughput Recorded   : {df['throughput_msg_sec'].max():,.0f} msgs/sec")
    print(f"Average Throughput         : {df['throughput_msg_sec'].mean():,.0f} msgs/sec")
    print(f"Overall Mean Latency       : {df['avg_latency_ns'].mean():.2f} ns")
    print(f"Approved Orders Avg Latency: {df['approved_avg_latency_ns'].mean():.2f} ns")
    print(f"Rejected Orders Avg Latency: {df['rejected_avg_latency_ns'].mean():.2f} ns")
    print(f"Minimum Observed Latency   : {min_lat_observed:.0f} ns")
    print(f"Maximum Observed Latency   : {df['max_latency_ns'].max():.0f} ns")
    print(f"Total Risk Approved Orders : {final_row['risk_approved']:,}")
    print(f"Total Risk Rejected Orders : {final_row['risk_rejected']:,}")
    print(f"Max SPSC Queue Backpressure: {df['spsc_queue_depth'].max()} items")
    print("====================================================\n")

    # Display concise DataFrame percentile description
    print("Pandas Metric Percentiles (25%, 50%, 75%):")
    print(df[["throughput_msg_sec", "avg_latency_ns", "spsc_queue_depth"]].describe().loc[["25%", "50%", "75%", "max"]].to_string())
    print()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Plot HFT FIX Engine telemetry time-series using Pandas.")
    parser.add_argument("--csv", default="fix_metrics_time_series.csv", help="Path to input telemetry CSV file.")
    parser.add_argument("--out", default="hft_performance_charts.png", help="Path for output PNG chart image.")
    parser.add_argument("--show", action="store_true", help="Display the plot on screen interactively.")
    args = parser.parse_args()

    plot_telemetry(args.csv, args.out, args.show)
